name: Haskell CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: [ 'latest', '8.6', '8.8', '8.10' ]
        cabal: [ '3.0' ]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1.1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
    - name: Cache cabal
      uses: actions/cache@v1
      with:
        path: ~/.cabal
        key: ghc-${{ matrix.ghc }}-cabal-${{ matrix.cabal }}-build-${{ github.sha }}
        restore-keys: |
          ghc-${{ matrix.ghc }}-cabal-${{ matrix.cabal }}-build
    - name: Prepare cabal
      run: |
         cabal update
         cabal build --only-dependencies
         cabal install hlint brittany --installdir=.
         sed -i "s/-Wall/-Wall -Werror/" taskwarrior.cabal
    - name: Build
      run: cabal build
    - name: Test
      run: cabal test
    - name: Build documentation
      run: |
         cabal haddock
         ! cabal haddock | grep "Missing documentation" -B1 > /dev/null
         ! cabal haddock | grep "is out of scope" -B1 > /dev/null
    - name: Run hlint
      run: ./hlint src
    - name: Check formatting
      run: ./brittany -c src/**/*.hs
