name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: [ '8.6.5', '8.8.1' ]
        cabal: [ '3.0' ]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
    - name: Update cabal
      run: cabal new-update
    - name: Build
      run: cabal new-build
    - name: Run tests
      run: cabal new-test
    - name: Run haddock
      run: cabal new-haddock
