name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: [ '8.6.5', '8.8.1' ]
        cabal: [ '3.0' ]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
      #    - name: Cache node modules
      #uses: actions/cache@v1
      #with:
      #  path: node_modules
      #  key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
      #  restore-keys: |
      #    ${{ runner.OS }}-build-${{ env.cache-name }}-
      #    ${{ runner.OS }}-build-
      #    ${{ runner.OS }}-

    - name: Prepare cabal
      run: |
         cabal new-update
         cabal new-build --only-dependencies
    - name: list
      run: ls -al
    - name: Build
      run: cabal new-build --ghc-option -Werror
    - name: Run tests
      run: cabal new-test
    - name: Run haddock
      run: cabal new-haddock
