name: Haskell CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: [ '8.8.1', '8.6.5', '8.4.4' ]
        cabal: [ '3.0' ]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
    - name: Cache cabal
      uses: actions/cache@v1
      with:
        path: ~/.cabal
        key: ghc-${{ matrix.ghc }}-cabal-${{ matrix.cabal }}-build-${{ github.sha }}
        restore-keys: |
          ghc-${{ matrix.ghc }}-cabal-${{ matrix.cabal }}-build
    - name: Prepare cabal
      run: |
         cabal new-update
         cabal new-build --only-dependencies
         cabal new-install hlint brittany --installdir=.
         sed -i "s/-Wall/-Wall -Werror/" taskwarrior.cabal
    - name: Build
      run: cabal new-build
    - name: Test
      run: cabal new-test
    - name: Build documentation
      run: |
         cabal new-haddock
         ! cabal new-haddock | grep "Missing documentation" -B1 > /dev/null
         ! cabal new-haddock | grep "is out of scope" -B1 > /dev/null
    - name: Run hlint
      run: ./hlint src
    - name: Check formatting
      run: ./brittany -c src/**/*.hs
