name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: [ '8.6.5', '8.8.1' ]
        cabal: [ '2.0', '3.0' ]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
    - name: Install dependencies
      run: |
        cabal update
        cabal install --only-dependencies --enable-tests
    - name: Build
      run: |
        cabal configure --enable-tests
        cabal build
    - name: Run tests
      run: cabal test
    - name: Run haddock
      run: cabal haddock
